version: "3.8"

services:
  pinjembuku_microservice:
    container_name: pinjembuku_microservice
    build:
      context: ./
      dockerfile: docker/api.Dockerfile
    ports:
      - "5001:5001"
      - "3001:3001"
      - "8001:8001"
    environment:
      - PORT=5001
    depends_on:
      - postgesql
      - redis
      - node_exporter
    restart: always
    volumes:
      - ./:/app
    networks:
      - pinjembuku_network

  redis:
    image: redis:6.0.9-alpine
    container_name: pinjembuku_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - pinjembuku_network

  postgesql:
    image: postgres:13-alpine
    container_name: pinjembuku_postgesql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pinjembuku_db
      - POSTGRES_HOST=5432
    command: -p 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - pinjembuku_network

  node_exporter:
    container_name: node_exporter_con
    image: prom/node-exporter
    ports:
      - '9101:9100'
    networks:
      - pinjembuku_network

networks:
  pinjembuku_network:
    driver: bridge