DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS librarians CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TYPE IF EXISTS role;
DROP TYPE IF EXISTS status;
DROP EXTENSION IF EXISTS citext CASCADE;